package config

// Defaults for daemon config when no config file is provided.
//
// Tokens are NOT hardcoded here. They come from the token_store block in the
// config JSON file, generated by secrets/generate-token-store.sh and injected
// by ops/config/generate-embedded-config.sh.
//
// These defaults are used only when the daemon starts without a --config flag
// (dev/test convenience). They return empty strings so the runtime knows no
// credentials are available.

// DefaultVKPeerID returns empty — no default peer without config.
func DefaultVKPeerID() string { return "" }

// DefaultVKDiscoveryPeerID returns empty — requires config file.
func DefaultVKDiscoveryPeerID() string { return "" }

// DefaultVKControlPeerID returns empty — requires config file.
func DefaultVKControlPeerID() string { return "" }

// DefaultVKLogsPeerID returns empty — requires config file.
func DefaultVKLogsPeerID() string { return "" }

// DefaultVKAdminPeerID returns empty — requires config file.
func DefaultVKAdminPeerID() string { return "" }

// DefaultVKChannels returns nil — requires config file with token_store.
func DefaultVKChannels() []VKChannelConfig { return nil }

// DefaultOKChannels returns nil — requires config file with token_store.
func DefaultOKChannels() []OKChannelConfig { return nil }

// DefaultVKChannelSet builds a VKChannelConfig slice from a role→peerID map.
// Useful for programmatic node bootstrapping without a config file.
func DefaultVKChannelSet(peerIDs map[string]string) []VKChannelConfig {
	if len(peerIDs) == 0 {
		return nil
	}
	out := make([]VKChannelConfig, 0, len(peerIDs))
	for role, pid := range peerIDs {
		out = append(out, VKChannelConfig{PeerID: pid, Role: role})
	}
	return out
}

// DefaultOKChannelSet builds an OKChannelConfig slice from a role→chatID map.
// Useful for programmatic node bootstrapping without a config file.
func DefaultOKChannelSet(chatIDs map[string]string) []OKChannelConfig {
	if len(chatIDs) == 0 {
		return nil
	}
	out := make([]OKChannelConfig, 0, len(chatIDs))
	for role, cid := range chatIDs {
		out = append(out, OKChannelConfig{ChatID: cid, Role: role})
	}
	return out
}

// DefaultVKToken returns empty — requires config file with token_store.
func DefaultVKToken() string { return "" }

// DefaultOKToken returns empty — requires config file with token_store.
func DefaultOKToken() string { return "" }

// DefaultOKChatID returns empty — requires config file.
func DefaultOKChatID() string { return "" }

// DefaultClientCarrierConfigs returns a minimal client config skeleton.
// Real credentials come from the config file's token_store block.
func DefaultClientCarrierConfigs(socksPort int, apiPort int) Config {
	return Config{
		Role:        RoleClient,
		ListenAPI:   "127.0.0.1:" + itoa(apiPort),
		SocksListen: "127.0.0.1:" + itoa(socksPort),
		Routing: RoutingConfig{
			Mode:       RouteModeNone,
			FullTunnel: true,
			DNSServers: []string{"1.1.1.1", "2606:4700:4700::1111"},
			MTU:        1500,
		},
		UpstreamProxy: UpstreamProxy{ClientEgressOnly: true},
	}
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	buf := make([]byte, 0, 10)
	for n > 0 {
		buf = append([]byte{byte('0' + n%10)}, buf...)
		n /= 10
	}
	return string(buf)
}
