package session

import (
	"bytes"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/meanwebuser/whitetransport/core/internal/fabric"
)

// EgressProfileVersion is the current typed session profile contract.
const EgressProfileVersion = 1

// EgressProfile is a short-lived client runtime profile issued by a node.
// URI and SSH credentials are never serialized outside the encrypted session
// payload. Version zero remains valid only for the legacy VLESS URI shape.
type EgressProfile struct {
	Version    int               `json:"version,omitempty"`
	EndpointID string            `json:"endpoint_id"`
	Carrier    string            `json:"carrier"`
	URI        string            `json:"uri,omitempty"`
	SSH        *SSHEgressProfile `json:"ssh,omitempty"`
}

// SSHEgressProfile contains portable, session-scoped SSH credentials.
// Filesystem paths, environment references and SSH agent configuration are
// intentionally absent so the decrypted profile can only be used in memory.
type SSHEgressProfile struct {
	Username                string   `json:"username"`
	PrivateKey              string   `json:"private_key"`
	PrivateKeyPassphrase    string   `json:"private_key_passphrase,omitempty"`
	HostKeys                []string `json:"host_keys"`
	ServerAliveIntervalSecs int      `json:"server_alive_interval_secs,omitempty"`
}

// SealEgressProfiles encrypts server-issued egress profiles with the unique
// session key generated by the client offer.
func SealEgressProfiles(sessionID, nodeID string, expiresAt time.Time, profiles []EgressProfile, key [32]byte) ([]byte, error) {
	createdAt := time.Now().UTC()
	ttl := expiresAt.Sub(createdAt)
	if ttl <= 0 {
		return nil, fmt.Errorf("egress profile expiry must be in the future")
	}
	if err := validateEgressProfiles(profiles); err != nil {
		return nil, err
	}
	payload, err := json.Marshal(profiles)
	if err != nil {
		return nil, fmt.Errorf("marshal egress profiles: %w", err)
	}
	payload, err = compressEgressProfiles(payload)
	if err != nil {
		return nil, err
	}
	cipher, err := fabric.NewSessionCipher(key)
	if err != nil {
		return nil, fmt.Errorf("create session cipher: %w", err)
	}
	return cipher.Seal(fabric.Envelope{
		Version: 1, ID: sessionID + ":egress-profiles", SessionID: sessionID,
		Source: nodeID, PayloadType: "session.egress_profiles", Payload: payload,
		TTL: ttl, CreatedAt: createdAt,
	})
}

// OpenEgressProfiles validates and decrypts the profile payload for one
// session. It rejects replies that are stale or bound to another session/node.
func OpenEgressProfiles(ciphertext []byte, sessionID, nodeID string, key [32]byte) ([]EgressProfile, error) {
	cipher, err := fabric.NewSessionCipher(key)
	if err != nil {
		return nil, fmt.Errorf("create session cipher: %w", err)
	}
	env, err := cipher.Open(ciphertext)
	if err != nil {
		return nil, fmt.Errorf("open egress profiles: %w", err)
	}
	if env.SessionID != sessionID || env.Source != nodeID || env.PayloadType != "session.egress_profiles" {
		return nil, fmt.Errorf("egress profiles do not match the active session")
	}
	if env.TTL <= 0 || !time.Now().UTC().Before(env.CreatedAt.Add(env.TTL)) {
		return nil, fmt.Errorf("egress profiles have expired")
	}
	payload, err := decompressEgressProfiles(env.Payload)
	if err != nil {
		return nil, err
	}
	var profiles []EgressProfile
	if err := json.Unmarshal(payload, &profiles); err != nil {
		return nil, fmt.Errorf("decode egress profiles: %w", err)
	}
	if err := validateEgressProfiles(profiles); err != nil {
		return nil, err
	}
	return profiles, nil
}

// validateEgressProfiles rejects ambiguous or non-portable credentials before
// they enter the encrypted wire format and again after decryption.
func validateEgressProfiles(profiles []EgressProfile) error {
	for i, profile := range profiles {
		if err := validateEgressProfile(profile); err != nil {
			return fmt.Errorf("validate egress profile %d: %w", i, err)
		}
	}
	return nil
}

func validateEgressProfile(profile EgressProfile) error {
	if strings.TrimSpace(profile.EndpointID) == "" {
		return fmt.Errorf("endpoint_id is required")
	}
	if strings.TrimSpace(profile.Carrier) == "" {
		return fmt.Errorf("carrier is required")
	}
	hasURI := strings.TrimSpace(profile.URI) != ""
	hasSSH := profile.SSH != nil
	if hasURI == hasSSH {
		return fmt.Errorf("exactly one VLESS URI or SSH payload is required")
	}
	if hasURI {
		if profile.Version != 0 && profile.Version != EgressProfileVersion {
			return fmt.Errorf("unsupported profile version %d", profile.Version)
		}
		if !strings.HasPrefix(strings.ToLower(strings.TrimSpace(profile.URI)), "vless://") {
			return fmt.Errorf("URI must use the vless scheme")
		}
		return nil
	}
	if profile.Version != EgressProfileVersion {
		return fmt.Errorf("SSH profile version must be %d", EgressProfileVersion)
	}
	if strings.TrimSpace(profile.SSH.Username) == "" {
		return fmt.Errorf("SSH username is required")
	}
	if strings.TrimSpace(profile.SSH.PrivateKey) == "" {
		return fmt.Errorf("SSH inline private key is required")
	}
	if len(profile.SSH.HostKeys) == 0 {
		return fmt.Errorf("at least one pinned SSH host key is required")
	}
	for _, hostKey := range profile.SSH.HostKeys {
		if strings.TrimSpace(hostKey) == "" {
			return fmt.Errorf("SSH host keys must not be empty")
		}
	}
	if profile.SSH.ServerAliveIntervalSecs < 0 {
		return fmt.Errorf("SSH keepalive interval must not be negative")
	}
	return nil
}

// compressEgressProfiles keeps multi-route session answers below control
// carrier limits. Xray profiles repeat host, SNI, UUID and transport fields,
// so compression happens before authenticated session encryption.
func compressEgressProfiles(payload []byte) ([]byte, error) {
	var compressed bytes.Buffer
	writer := gzip.NewWriter(&compressed)
	if _, err := writer.Write(payload); err != nil {
		return nil, fmt.Errorf("compress egress profiles: %w", err)
	}
	if err := writer.Close(); err != nil {
		return nil, fmt.Errorf("finish egress profile compression: %w", err)
	}
	return compressed.Bytes(), nil
}

// decompressEgressProfiles reads the current compressed wire format.
// Deprecated: the JSON fallback only supports answers issued before profile
// compression and must be removed after all deployed clients consume the
// compressed profile contract.
func decompressEgressProfiles(payload []byte) ([]byte, error) {
	reader, err := gzip.NewReader(bytes.NewReader(payload))
	if err != nil {
		return payload, nil
	}
	decompressed, err := io.ReadAll(reader)
	if err != nil {
		_ = reader.Close()
		return nil, fmt.Errorf("decompress egress profiles: %w", err)
	}
	if err := reader.Close(); err != nil {
		return nil, fmt.Errorf("close egress profile decompressor: %w", err)
	}
	return decompressed, nil
}
