import type {
  ChannelPayload,
  ControlMessageKind,
  ProviderHealth,
  TransportEndpoint,
} from './index.js';

export const CONTROL_MESSAGE_VERSION = 1;

export type ControlActorRole = "client" | "server" | "creator" | "admin" | "provider";

export interface ControlActor {
  /** Stable actor id inside one deployment or room. */
  readonly id: string;
  /** Actor role used by clients, servers, admin UI, and providers. */
  readonly role: ControlActorRole;
  /** Human readable actor label safe for admin UI. */
  readonly label?: string;
  /** Runtime platform such as ios, android, web, desktop, or server. */
  readonly platform?: string;
  /** Application/runtime version when known. */
  readonly version?: string;
}

export type RoomLifecycleState = "announced" | "joining" | "ready" | "degraded" | "offline";

export interface RoomProviderSnapshot {
  /** Provider instance represented in the room state. */
  readonly providerId: string;
  /** Most recent provider health known to the announcing actor. */
  readonly health: ProviderHealth;
  /** Lower number means more preferred when policy has no stronger rule. */
  readonly priority?: number;
}

export interface RoomStateControlBody {
  /** Stable room id or room URL fingerprint. */
  readonly roomId: string;
  /** Monotonic room revision from the announcing actor. */
  readonly revision: number;
  /** Current room lifecycle state. */
  readonly state: RoomLifecycleState;
  /** Stream endpoints currently valid for the room. */
  readonly endpoints: readonly TransportEndpoint[];
  /** Provider health snapshots used by failover and admin UI. */
  readonly providers: readonly RoomProviderSnapshot[];
}

export type ClientFeedbackSeverity = "info" | "warning" | "error";

export type ClientFeedbackCode =
  | "connected"
  | "disconnected"
  | "provider_failed"
  | "endpoint_failed"
  | "latency_sample"
  | "user_action";

export interface ClientFeedbackControlBody {
  /** Client instance id. */
  readonly clientId: string;
  /** Feedback severity for admin UI and policy decisions. */
  readonly severity: ClientFeedbackSeverity;
  /** Machine-readable feedback reason. */
  readonly code: ClientFeedbackCode;
  /** Short operator-safe message. */
  readonly message: string;
  /** Provider involved in the feedback, when applicable. */
  readonly providerId?: string;
  /** Transport endpoint involved in the feedback, when applicable. */
  readonly endpointId?: string;
  /** Millisecond timestamp from the observing client. */
  readonly observedAt: number;
  /** Small string-only details safe for logs and admin UI. */
  readonly metadata?: Readonly<Record<string, string>>;
}

export type AdminCommandAction =
  | "refresh_discovery"
  | "rotate_room"
  | "enable_provider"
  | "disable_provider"
  | "set_provider_priority"
  | "restart_transport";

export interface AdminCommandControlBody {
  /** Idempotency key generated by the admin surface. */
  readonly commandId: string;
  /** Command action understood by clients, servers, or providers. */
  readonly action: AdminCommandAction;
  /** Target actor, provider, endpoint, or room id. */
  readonly targetId?: string;
  /** String-only command arguments to avoid per-client JSON drift. */
  readonly arguments?: Readonly<Record<string, string>>;
}

export type ProviderProbePhase = "request" | "result";

export interface ProviderProbeControlBody {
  /** Probe id shared by request and result. */
  readonly probeId: string;
  /** Whether this message asks for a probe or reports a result. */
  readonly phase: ProviderProbePhase;
  /** Provider to probe or provider that returned the result. */
  readonly providerId: string;
  /** Endpoint involved in a stream-provider probe, when applicable. */
  readonly endpoint?: TransportEndpoint;
  /** Health result for completed probes. */
  readonly health?: ProviderHealth;
}

export interface TransportEndpointControlBody {
  /** Endpoint discovered or refreshed by a provider/control-plane actor. */
  readonly endpoint: TransportEndpoint;
  /** Provider that discovered or currently owns the endpoint. */
  readonly sourceProviderId: string;
  /** Millisecond timestamp when the endpoint was observed. */
  readonly discoveredAt: number;
  /** Optional validity window for room discovery and failover. */
  readonly ttlMs?: number;
  /** Lower number means more preferred when policy has no stronger rule. */
  readonly priority?: number;
}

export interface TransportPayloadControlBody {
  /** Endpoint carrying this stream payload. */
  readonly endpointId: string;
  /** Logical stream id inside the endpoint. */
  readonly streamId: string;
  /** Monotonic chunk sequence inside the stream. */
  readonly sequence: number;
  /** Base64-encoded binary chunk for provider-log transports. */
  readonly chunkBase64: string;
  /** True when this is the final chunk for the stream. */
  readonly final?: boolean;
}

export interface ControlMessageBodyByKind {
  readonly room_state: RoomStateControlBody;
  readonly client_feedback: ClientFeedbackControlBody;
  readonly admin_command: AdminCommandControlBody;
  readonly provider_probe: ProviderProbeControlBody;
  readonly transport_endpoint: TransportEndpointControlBody;
  readonly transport_payload: TransportPayloadControlBody;
}

export type ControlMessageBody = ControlMessageBodyByKind[ControlMessageKind];

export interface ControlEnvelope<K extends ControlMessageKind = ControlMessageKind> {
  /** Schema version for all shared control messages. */
  readonly version: typeof CONTROL_MESSAGE_VERSION;
  /** Idempotency/message id generated by the sender. */
  readonly id: string;
  /** Logical message kind, mirrored into ChannelPayload.kind. */
  readonly kind: K;
  /** Monotonic sender timestamp in milliseconds. */
  readonly createdAt: number;
  /** Actor that created this message. */
  readonly source: ControlActor;
  /** Typed body for the selected message kind. */
  readonly body: ControlMessageBodyByKind[K];
}

export interface CreateControlEnvelopeOptions<K extends ControlMessageKind> {
  readonly id: string;
  readonly kind: K;
  readonly source: ControlActor;
  readonly body: ControlMessageBodyByKind[K];
  readonly createdAt?: number;
}

export interface EncodeControlPayloadOptions {
  readonly expiresAt?: number;
  readonly metadata?: Readonly<Record<string, string>>;
}

const textEncoder = new TextEncoder();
const textDecoder = new TextDecoder();

/**
 * Creates a typed control envelope with the current schema version.
 *
 * @param options Envelope fields supplied by the caller.
 * @returns Versioned control envelope.
 */
export function createControlEnvelope<K extends ControlMessageKind>(
  options: CreateControlEnvelopeOptions<K>,
): ControlEnvelope<K> {
  return {
    version: CONTROL_MESSAGE_VERSION,
    id: options.id,
    kind: options.kind,
    createdAt: options.createdAt ?? Date.now(),
    source: options.source,
    body: options.body,
  };
}

/**
 * Encodes a typed control envelope into provider-channel payload bytes.
 *
 * @param envelope Control envelope to send.
 * @param options Optional expiry and metadata.
 * @returns Channel payload containing JSON envelope bytes.
 */
export function encodeControlPayload<K extends ControlMessageKind>(
  envelope: ControlEnvelope<K>,
  options: EncodeControlPayloadOptions = {},
): ChannelPayload {
  assertControlEnvelope(envelope, envelope.kind);
  return {
    kind: envelope.kind,
    createdAt: envelope.createdAt,
    expiresAt: options.expiresAt,
    body: textEncoder.encode(JSON.stringify(envelope)),
    metadata: {
      ...options.metadata,
      "control.id": envelope.id,
      "control.version": String(envelope.version),
      "control.source": envelope.source.id,
    },
  };
}

/**
 * Decodes provider-channel payload bytes into a typed control envelope.
 *
 * @param payload Provider-channel payload received from any provider.
 * @returns Parsed and minimally validated control envelope.
 * @throws If JSON, version, kind, source, or body shape is invalid.
 */
export function decodeControlPayload<K extends ControlMessageKind>(
  payload: ChannelPayload & { readonly kind: K },
): ControlEnvelope<K> {
  const rawText = textDecoder.decode(payload.body);
  const parsed: unknown = JSON.parse(rawText);
  return assertControlEnvelope(parsed, payload.kind);
}

function assertControlEnvelope<K extends ControlMessageKind>(
  value: unknown,
  expectedKind: K,
): ControlEnvelope<K> {
  if (!isRecord(value)) throw new Error("Control envelope must be a JSON object");
  if (value.version !== CONTROL_MESSAGE_VERSION) {
    throw new Error(`Unsupported control envelope version: ${String(value.version)}`);
  }
  if (value.kind !== expectedKind) {
    throw new Error(`Control envelope kind mismatch: expected ${expectedKind}, got ${String(value.kind)}`);
  }
  assertNonEmptyString(value.id, "Control envelope id is required");
  assertNumber(value.createdAt, "Control envelope createdAt is required");
  assertControlActor(value.source);
  if (!isRecord(value.body)) throw new Error("Control envelope body must be a JSON object");
  return value as unknown as ControlEnvelope<K>;
}

function assertControlActor(value: unknown): asserts value is ControlActor {
  if (!isRecord(value)) throw new Error("Control envelope source must be a JSON object");
  assertNonEmptyString(value.id, "Control envelope source.id is required");
  assertNonEmptyString(value.role, "Control envelope source.role is required");
}

function assertNonEmptyString(value: unknown, message: string): asserts value is string {
  if (typeof value !== "string" || value.trim().length === 0) throw new Error(message);
}

function assertNumber(value: unknown, message: string): asserts value is number {
  if (typeof value !== "number" || !Number.isFinite(value)) throw new Error(message);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
