#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";
import { WebSocket } from "ws";
const origin=process.env.MOBILE_BROWSER_ORIGIN||"http://127.0.0.1:8080";
const cdpOrigin=process.env.CDP_ORIGIN||"http://127.0.0.1:9222";
const outDir=process.env.OUT_DIR||"artifacts/transport-smoke/"+new Date().toISOString().replace(/[:.]/g,"-");
const pass=process.env.MOBILE_BROWSER_PASSWORD||"";
const bareTransport=process.env.BARE_TRANSPORT||"libcurl";
const transports=(process.env.TRANSPORTS||"wb,wisp,scramjet-v1,ultraviolet,render,anticors").split(",").filter(Boolean);
const urls=(process.env.URLS||"https://chatgpt.com/,https://web.telegram.org/,https://www.youtube.com/,https://chat.z.ai/,https://chat.qwen.ai/,https://chat.deepseek.com/,https://grok.com/,https://www.instagram.com/,https://www.facebook.com/,https://www.tiktok.com/,https://x.com/,https://web.whatsapp.com/,https://discord.com/app,https://app.element.io/").split(",").filter(Boolean);
const waitMs=Number(process.env.LOAD_WAIT_MS||9000);
await fs.mkdir(outDir,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const esc=s=>String(s??"").replace(/"/g,"\"\"").replace(/\n/g," ");
const slug=s=>s.replace(/^https?:\/\//,"").replace(/[^a-z0-9.-]+/gi,"_").slice(0,70);
async function json(url,opts){const r=await fetch(url,opts);if(!r.ok)throw new Error(url+" -> "+r.status);return r.json();}
class CDP{constructor(wsUrl){this.ws=new WebSocket(wsUrl);this.id=1;this.pending=new Map();this.console=[];this.net=[];this.ready=new Promise((res,rej)=>{this.ws.on("open",res);this.ws.on("error",rej);});this.ws.on("message",buf=>{const m=JSON.parse(buf.toString());if(m.id&&this.pending.has(m.id)){const p=this.pending.get(m.id);this.pending.delete(m.id);m.error?p.reject(new Error(JSON.stringify(m.error))):p.resolve(m.result||{});return;}if(m.method==="Runtime.consoleAPICalled")this.console.push({type:m.params.type,text:(m.params.args||[]).map(a=>a.value??a.description??a.type).join(" ")});if(m.method==="Runtime.exceptionThrown")this.console.push({type:"exception",text:m.params.exceptionDetails?.exception?.description||m.params.exceptionDetails?.text||"exception"});if(m.method==="Network.responseReceived")this.net.push({url:m.params.response.url,status:m.params.response.status,type:m.params.type});if(m.method==="Network.loadingFailed")this.net.push({error:m.params.errorText,type:m.params.type,failed:true});});}async send(method,params={}){await this.ready;const id=this.id++;const p=new Promise((resolve,reject)=>this.pending.set(id,{resolve,reject}));this.ws.send(JSON.stringify({id,method,params}));return p;}async eval(expr){const r=await this.send("Runtime.evaluate",{expression:expr,awaitPromise:true,returnByValue:true,userGesture:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text||"eval failed");return r.result?.value;}async close(){try{await this.send("Page.close");}catch{}try{this.ws.close();}catch{}}}
async function newPage(){let t;try{t=await json(cdpOrigin+"/json/new?"+encodeURIComponent("about:blank"),{method:"PUT"});}catch{t=await json(cdpOrigin+"/json/new?"+encodeURIComponent("about:blank"));}const c=new CDP(t.webSocketDebuggerUrl);await c.send("Page.enable");await c.send("Runtime.enable");await c.send("Network.enable");return c;}
async function setup(c,transport){const u=pass?origin+"/?p="+encodeURIComponent(pass):origin+"/";await c.send("Page.navigate",{url:u});await sleep(1600);await c.eval("localStorage.setItem(\"mobile-browser:settings\", JSON.stringify({logs:true,barPosition:\"bottom\",autohide:false,transport:"+JSON.stringify(transport)+"})); localStorage.setItem(\"mobile-browser:debug-log\",\"[]\"); true");await c.send("Page.navigate",{url:origin+"/"});await sleep(2200);}
async function testOne(transport,url){const c=await newPage();const started=Date.now();const r={transport,url,ok:false,verdict:"unknown",status:"",frame:"",errors:"",netErrors:"",screenshot:""};try{await setup(c,transport);c.console.length=0;c.net.length=0;await c.eval("document.getElementById(\"sj-address\").value="+JSON.stringify(url)+"; document.getElementById(\"sj-form\").requestSubmit(); true");await sleep(waitMs);const s=await c.eval("(() => { const f=document.querySelector(\"#browser-stage iframe\"); const cv=document.querySelector(\"#browser-stage canvas\"); const dbg=document.getElementById(\"debug-log\")?.innerText||\"\"; const st=document.getElementById(\"bar-status\")?.innerText||\"\"; let fi={}; try{fi=f?{src:f.src,title:f.contentDocument?.title||\"\",text:(f.contentDocument?.body?.innerText||\"\").slice(0,500)}:{}}catch(e){fi=f?{src:f.src,cross:true}:{}} return {hasIframe:!!f,hasCanvas:!!cv,frame:fi,status:st,debug:dbg.slice(-2500),body:(document.body.innerText||\"\").slice(0,800)} })()");const shot=await c.send("Page.captureScreenshot",{format:"png",captureBeyondViewport:false}).catch(()=>null);if(shot?.data){r.screenshot=path.join(outDir,transport+"__"+slug(url)+".png");await fs.writeFile(r.screenshot,Buffer.from(shot.data,"base64"));}const errs=c.console.filter(x=>["error","exception","assert"].includes(x.type)).map(x=>x.text).slice(-8);const nets=c.net.filter(x=>x.failed||x.status>=400).slice(-12);r.status=s.status||"";r.frame=s.frame?.src||"";r.errors=errs.join(" | ");r.netErrors=nets.map(x=>(x.status||x.error)+":"+(x.url||x.type||"")).join(" | ");r.body=(s.frame?.text||s.body||"").replace(/\s+/g," ").slice(0,300);const host=new URL(url).hostname.replace(/^www\./,"");const saw=(r.frame+r.status+s.debug).includes(host)||(transport==="render"&&s.hasCanvas);const visual=s.hasCanvas||s.hasIframe;const errorPage=/Error processing your request|Internal Server Error|Failed to load/i.test(r.body+" "+s.debug);const fatal=/Failed to register|No service worker|blocked_url|address form not found|Ultraviolet bundle\/config is not loaded|Service worker activation timeout/i.test(r.errors+" "+r.body+" "+s.debug)||errorPage;const netBad=nets.some(x=>x.status>=500||(x.failed&&x.error!=="net::ERR_ABORTED"&&/Document|Fetch|XHR/i.test(x.type||"")));r.ok=Boolean(saw&&visual&&!fatal&&!netBad);r.verdict=r.ok?"open-attempt-ok":errorPage?"proxy-error-page":fatal?"js-error":netBad?"network-failures":visual?"partial-visual-check":"no-frame";}catch(e){r.verdict="runner-error";r.errors=String(e.stack||e).slice(0,500);}finally{r.elapsedMs=Date.now()-started;await c.close();}return r;}
const rows=[];for(const t of transports)for(const u of urls){process.stdout.write("TEST "+t+" "+u+" ... ");const r=await testOne(t,u);rows.push(r);console.log((r.ok?"OK ":"FAIL ")+r.verdict);}await fs.writeFile(path.join(outDir,"results.json"),JSON.stringify({origin,transports,urls,rows},null,2));let csv="transport,url,ok,verdict,status,frame,errors,netErrors,screenshot\n";for(const r of rows)csv+=[r.transport,r.url,r.ok?"1":"0",r.verdict,r.status,r.frame,r.errors,r.netErrors,r.screenshot].map(v=>"\""+esc(v)+"\"").join(",")+"\n";await fs.writeFile(path.join(outDir,"results.csv"),csv);const sums={};for(const r of rows){sums[r.transport]||={ok:0,fail:0};r.ok?sums[r.transport].ok++:sums[r.transport].fail++;}let md="# Transport smoke test\n\nOrigin: "+origin+"\n\nBareMux backend: "+bareTransport+"\n\n## Summary\n\n| transport | OK | FAIL |\n|---|---:|---:|\n";for(const [t,s] of Object.entries(sums))md+="| "+t+" | "+s.ok+" | "+s.fail+" |\n";md+="\n## Matrix\n\n| transport | site | result | verdict | note |\n|---|---|---|---|---|\n";for(const r of rows)md+="| "+r.transport+" | "+r.url+" | "+(r.ok?"OK":"FAIL")+" | "+r.verdict+" | "+esc(r.errors||r.netErrors||r.status).slice(0,160).replace(/\|/g,"/")+" |\n";await fs.writeFile(path.join(outDir,"summary.md"),md);console.log("\nReport: "+outDir+"/summary.md");
