// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddClientCredential(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddClientCredential'](arg1, arg2, arg3, arg4, arg5);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function CopyLogs() {
  return window['go']['main']['App']['CopyLogs']();
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetCapabilities() {
  return window['go']['main']['App']['GetCapabilities']();
}

export function GetClientCredentialRefreshMessage() {
  return window['go']['main']['App']['GetClientCredentialRefreshMessage']();
}

export function GetLogFilePath() {
  return window['go']['main']['App']['GetLogFilePath']();
}

export function GetRoutingSettings() {
  return window['go']['main']['App']['GetRoutingSettings']();
}

export function GetRuntimeResources() {
  return window['go']['main']['App']['GetRuntimeResources']();
}

export function GetRuntimeSupervisorStatus() {
  return window['go']['main']['App']['GetRuntimeSupervisorStatus']();
}

export function GetSplitRoutingSettings() {
  return window['go']['main']['App']['GetSplitRoutingSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetSupportedPlatforms() {
  return window['go']['main']['App']['GetSupportedPlatforms']();
}

export function GetTelemetry() {
  return window['go']['main']['App']['GetTelemetry']();
}

export function HasClientRoomCredentials() {
  return window['go']['main']['App']['HasClientRoomCredentials']();
}

export function ImportBrowserExport(arg1) {
  return window['go']['main']['App']['ImportBrowserExport'](arg1);
}

export function ListClientCredentials() {
  return window['go']['main']['App']['ListClientCredentials']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ProbeMacAuthorization() {
  return window['go']['main']['App']['ProbeMacAuthorization']();
}

export function ReadLogs(arg1) {
  return window['go']['main']['App']['ReadLogs'](arg1);
}

export function RemoveClientCredential(arg1) {
  return window['go']['main']['App']['RemoveClientCredential'](arg1);
}

export function RequestSystemVPNPermission() {
  return window['go']['main']['App']['RequestSystemVPNPermission']();
}

export function RunDiagnostics() {
  return window['go']['main']['App']['RunDiagnostics']();
}

export function RunTestMode(arg1) {
  return window['go']['main']['App']['RunTestMode'](arg1);
}

export function SetRoutingSettings(arg1, arg2) {
  return window['go']['main']['App']['SetRoutingSettings'](arg1, arg2);
}

export function SetSplitRoutingSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSplitRoutingSettings'](arg1, arg2, arg3);
}

export function StartSystemVPN() {
  return window['go']['main']['App']['StartSystemVPN']();
}

export function StopSystemVPN() {
  return window['go']['main']['App']['StopSystemVPN']();
}
