// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';
import {main} from '../models';

export function AddClientCredential(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Array<runtime.ClientCredentialSummary>>;

export function BeginRoomAuth():Promise<main.roomAuthStatus>;

export function Connect(arg1:string):Promise<runtime.DesktopStatus>;

export function CopyLogs():Promise<string>;

export function Disconnect():Promise<runtime.DesktopStatus>;

export function GetCapabilities():Promise<main.nativeCapabilities>;

export function GetClientCredentialRefreshMessage():Promise<string>;

export function GetLogFilePath():Promise<string>;

export function GetRoomAuthStatus():Promise<main.roomAuthStatus>;

export function GetRoutingSettings():Promise<main.routingSettings>;

export function GetRuntimeResources():Promise<runtime.RuntimeResourceSummary>;

export function GetRuntimeSupervisorStatus():Promise<runtime.DaemonSupervisorStatus>;

export function GetSplitRoutingSettings():Promise<main.splitRoutingSettings>;

export function GetStatus():Promise<runtime.DesktopStatus>;

export function GetSupportedPlatforms():Promise<Array<string>>;

export function GetTelemetry():Promise<runtime.DesktopTelemetry>;

export function HasClientRoomCredentials():Promise<boolean>;

export function ImportBrowserExport(arg1:string):Promise<Array<runtime.ClientCredentialSummary>>;

export function ListClientCredentials():Promise<Array<runtime.ClientCredentialSummary>>;

export function ListServers():Promise<Array<runtime.ServerSummary>>;

export function ProbeMacAuthorization():Promise<main.macOSAuthorizationProbeResult>;

export function ReadLogs(arg1:number):Promise<Array<runtime.LogLine>>;

export function RemoveClientCredential(arg1:string):Promise<Array<runtime.ClientCredentialSummary>>;

export function RequestSystemVPNPermission():Promise<runtime.SystemVPNState>;

export function RunDiagnostics():Promise<runtime.DiagnosticResult>;

export function RunTestMode(arg1:string):Promise<main.launchConnectResult>;

export function SetRoutingSettings(arg1:string,arg2:boolean):Promise<main.routingSettings>;

export function SetSplitRoutingSettings(arg1:string,arg2:boolean,arg3:Array<string>):Promise<main.splitRoutingSettings>;

export function StartSystemVPN():Promise<runtime.DesktopStatus>;

export function StopSystemVPN():Promise<runtime.SystemVPNState>;
